### ISSUE TITLE
authtoken error

### ISSUE THREAD

**Issue by ghost** [jemise111/dj-lazy#1]
penetrance~ dj-lazy
/usr/local/lib/node_modules/dj-lazy/lib/index.js:61
if (authToken) {
    ^

ReferenceError: authToken is not defined
    at Object.<anonymous> (/usr/local/lib/node_modules/dj-lazy/lib/index.js:61:5)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)
    at startup (node.js:141:18)
    at node.js:933:3

I'm on a MacBook Pro OS X 10.11.3. I installed node using homebrew (brew install node).

**Comment by jemise111** [comment]
@penetrance apologies, some old code got in there.

Just updated the package. Can you try npm uninstalling and re-installing? Thanks!

**Comment by ghost** [comment]
@jemise111 thanks for the quick fix! it works amazing now. this is a really neat tool, thanks for taking the time to make it.

**Comment by jemise111** [comment]
@penetrance Awesome, glad you're enjoying it!
